resources:
  - ../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-apiserver
      namespace: test
    $patch: delete
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: ext-api
      namespace: test
    $patch: delete
