apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.example.toddtreece.com
spec:
  insecureSkipTLSVerify: true
  group: example.toddtreece.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: ext-api
    namespace: test
    port: 8443
  version: v1beta1

---

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.query.toddtreece.com
spec:
  insecureSkipTLSVerify: true
  group: query.toddtreece.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: ext-api
    namespace: test
    port: 8443
  version: v1
