apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-apiserver
  namespace: test
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: test-apiserver
      containers:
        - name: test-apiserver
          image: localhost:5000/test-apiserver:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/tmp/test-apiserver"
              name: resource-storage
      volumes:
        - name: resource-storage
          emptyDir:
            sizeLimit: 500Mi
